version: '3.8'

services:
  app:
    build: ./backend
    container_name: judge-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./problems:/problems
      - ./.env:/opt/app/.env
    networks:
      - backend

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - backend

  redis:
    image: "redis:latest"
    container_name: redis-server
    volumes:
      - data:/data
    restart: always
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge

